name: CI/CD Pipeline

on:
  push:
    branches: [ main, "feature/*" ]
  pull_request:
    branches: [ main ]

jobs:
  testes-e-alertas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Executar Testes Unitários
        run: python -m unittest test_main.py

      - name: Enviar alerta para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🚀 Alerta DevOps: Um novo commit ou PR foi processado pelo GitHub Actions!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}