name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Executar Testes Unitários
        run: python -m unittest test_main.py

      # Atenção: Se você fez a atividade da Semana 6 (Alertas), 
      # cole o código do seu alerta (Slack, Email, etc.) logo aqui abaixo!